import {
  Atom,
  Boxes,
  Braces,
  Cloud,
  Coffee,
  Container,
  Database,
  FileCode2,
  FlaskConical,
  GitBranch,
  Globe,
  Hexagon,
  Layers,
  Leaf,
  Package,
  RefreshCcw,
  Server,
  Ship,
  SquareTerminal,
  Workflow,
  Zap,
  type LucideIcon,
} from 'lucide-react'
import type { TechIcon } from '@/types'

export const techIcons: Record<TechIcon, LucideIcon> = {
  coffee: Coffee,
  leaf: Leaf,
  workflow: Workflow,
  database: Database,
  container: Container,
  flask: FlaskConical,
  package: Package,
  layers: Layers,
  atom: Atom,
  server: Server,
  'file-code': FileCode2,
  boxes: Boxes,
  'git-branch': GitBranch,
  refresh: RefreshCcw,
  terminal: SquareTerminal,
  ship: Ship,
  cloud: Cloud,
  braces: Braces,
  hexagon: Hexagon,
  zap: Zap,
  globe: Globe,
}
